/*
Suger API

CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

API version: 1.0
Contact: support@suger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package suger

import (
	"encoding/json"
	"time"
)

// checks if the GcpMarketplacePrivateOfferReplacementMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpMarketplacePrivateOfferReplacementMetadata{}

// GcpMarketplacePrivateOfferReplacementMetadata struct for GcpMarketplacePrivateOfferReplacementMetadata
type GcpMarketplacePrivateOfferReplacementMetadata struct {
	CotermAlignment *string `json:"cotermAlignment,omitempty"`
	// The resource name of the private offer being replaced. in format of \"projects/{projectNumber}/services/{productServiceName}/privateOffers/{privateOfferId}\"
	ReplacedOffer        *string    `json:"replacedOffer,omitempty"`
	ReplacedOfferEndTime *time.Time `json:"replacedOfferEndTime,omitempty"`
	ReplacementPolicy    *string    `json:"replacementPolicy,omitempty"`
}

// NewGcpMarketplacePrivateOfferReplacementMetadata instantiates a new GcpMarketplacePrivateOfferReplacementMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpMarketplacePrivateOfferReplacementMetadata() *GcpMarketplacePrivateOfferReplacementMetadata {
	this := GcpMarketplacePrivateOfferReplacementMetadata{}
	return &this
}

// NewGcpMarketplacePrivateOfferReplacementMetadataWithDefaults instantiates a new GcpMarketplacePrivateOfferReplacementMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpMarketplacePrivateOfferReplacementMetadataWithDefaults() *GcpMarketplacePrivateOfferReplacementMetadata {
	this := GcpMarketplacePrivateOfferReplacementMetadata{}
	return &this
}

// GetCotermAlignment returns the CotermAlignment field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetCotermAlignment() string {
	if o == nil || IsNil(o.CotermAlignment) {
		var ret string
		return ret
	}
	return *o.CotermAlignment
}

// GetCotermAlignmentOk returns a tuple with the CotermAlignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetCotermAlignmentOk() (*string, bool) {
	if o == nil || IsNil(o.CotermAlignment) {
		return nil, false
	}
	return o.CotermAlignment, true
}

// HasCotermAlignment returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) HasCotermAlignment() bool {
	if o != nil && !IsNil(o.CotermAlignment) {
		return true
	}

	return false
}

// SetCotermAlignment gets a reference to the given string and assigns it to the CotermAlignment field.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) SetCotermAlignment(v string) {
	o.CotermAlignment = &v
}

// GetReplacedOffer returns the ReplacedOffer field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetReplacedOffer() string {
	if o == nil || IsNil(o.ReplacedOffer) {
		var ret string
		return ret
	}
	return *o.ReplacedOffer
}

// GetReplacedOfferOk returns a tuple with the ReplacedOffer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetReplacedOfferOk() (*string, bool) {
	if o == nil || IsNil(o.ReplacedOffer) {
		return nil, false
	}
	return o.ReplacedOffer, true
}

// HasReplacedOffer returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) HasReplacedOffer() bool {
	if o != nil && !IsNil(o.ReplacedOffer) {
		return true
	}

	return false
}

// SetReplacedOffer gets a reference to the given string and assigns it to the ReplacedOffer field.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) SetReplacedOffer(v string) {
	o.ReplacedOffer = &v
}

// GetReplacedOfferEndTime returns the ReplacedOfferEndTime field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetReplacedOfferEndTime() time.Time {
	if o == nil || IsNil(o.ReplacedOfferEndTime) {
		var ret time.Time
		return ret
	}
	return *o.ReplacedOfferEndTime
}

// GetReplacedOfferEndTimeOk returns a tuple with the ReplacedOfferEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetReplacedOfferEndTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ReplacedOfferEndTime) {
		return nil, false
	}
	return o.ReplacedOfferEndTime, true
}

// HasReplacedOfferEndTime returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) HasReplacedOfferEndTime() bool {
	if o != nil && !IsNil(o.ReplacedOfferEndTime) {
		return true
	}

	return false
}

// SetReplacedOfferEndTime gets a reference to the given time.Time and assigns it to the ReplacedOfferEndTime field.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) SetReplacedOfferEndTime(v time.Time) {
	o.ReplacedOfferEndTime = &v
}

// GetReplacementPolicy returns the ReplacementPolicy field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetReplacementPolicy() string {
	if o == nil || IsNil(o.ReplacementPolicy) {
		var ret string
		return ret
	}
	return *o.ReplacementPolicy
}

// GetReplacementPolicyOk returns a tuple with the ReplacementPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) GetReplacementPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.ReplacementPolicy) {
		return nil, false
	}
	return o.ReplacementPolicy, true
}

// HasReplacementPolicy returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) HasReplacementPolicy() bool {
	if o != nil && !IsNil(o.ReplacementPolicy) {
		return true
	}

	return false
}

// SetReplacementPolicy gets a reference to the given string and assigns it to the ReplacementPolicy field.
func (o *GcpMarketplacePrivateOfferReplacementMetadata) SetReplacementPolicy(v string) {
	o.ReplacementPolicy = &v
}

func (o GcpMarketplacePrivateOfferReplacementMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpMarketplacePrivateOfferReplacementMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CotermAlignment) {
		toSerialize["cotermAlignment"] = o.CotermAlignment
	}
	if !IsNil(o.ReplacedOffer) {
		toSerialize["replacedOffer"] = o.ReplacedOffer
	}
	if !IsNil(o.ReplacedOfferEndTime) {
		toSerialize["replacedOfferEndTime"] = o.ReplacedOfferEndTime
	}
	if !IsNil(o.ReplacementPolicy) {
		toSerialize["replacementPolicy"] = o.ReplacementPolicy
	}
	return toSerialize, nil
}

type NullableGcpMarketplacePrivateOfferReplacementMetadata struct {
	value *GcpMarketplacePrivateOfferReplacementMetadata
	isSet bool
}

func (v NullableGcpMarketplacePrivateOfferReplacementMetadata) Get() *GcpMarketplacePrivateOfferReplacementMetadata {
	return v.value
}

func (v *NullableGcpMarketplacePrivateOfferReplacementMetadata) Set(val *GcpMarketplacePrivateOfferReplacementMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpMarketplacePrivateOfferReplacementMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpMarketplacePrivateOfferReplacementMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpMarketplacePrivateOfferReplacementMetadata(val *GcpMarketplacePrivateOfferReplacementMetadata) *NullableGcpMarketplacePrivateOfferReplacementMetadata {
	return &NullableGcpMarketplacePrivateOfferReplacementMetadata{value: val, isSet: true}
}

func (v NullableGcpMarketplacePrivateOfferReplacementMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpMarketplacePrivateOfferReplacementMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
