/*
Suger API

CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

API version: 1.0
Contact: support@suger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package suger

import (
	"encoding/json"
	"fmt"
)

// AzureMarketplacePrivateOfferType the model 'AzureMarketplacePrivateOfferType'
type AzureMarketplacePrivateOfferType string

// List of AzureMarketplacePrivateOfferType
const (
	AzureMarketplacePrivateOfferType_unknown                           AzureMarketplacePrivateOfferType = ""
	AzureMarketplacePrivateOfferType_customerPromotion                 AzureMarketplacePrivateOfferType = "customerPromotion"
	AzureMarketplacePrivateOfferType_cspPromotion                      AzureMarketplacePrivateOfferType = "cspPromotion"
	AzureMarketplacePrivateOfferType_multipartyPromotionChannelPartner AzureMarketplacePrivateOfferType = "multipartyPromotionChannelPartner"
	AzureMarketplacePrivateOfferType_multipartyPromotionOriginator     AzureMarketplacePrivateOfferType = "multipartyPromotionOriginator"
)

// All allowed values of AzureMarketplacePrivateOfferType enum
var AllowedAzureMarketplacePrivateOfferTypeEnumValues = []AzureMarketplacePrivateOfferType{
	"",
	"customerPromotion",
	"cspPromotion",
	"multipartyPromotionChannelPartner",
	"multipartyPromotionOriginator",
}

func (v *AzureMarketplacePrivateOfferType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AzureMarketplacePrivateOfferType(value)
	for _, existing := range AllowedAzureMarketplacePrivateOfferTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AzureMarketplacePrivateOfferType", value)
}

// NewAzureMarketplacePrivateOfferTypeFromValue returns a pointer to a valid AzureMarketplacePrivateOfferType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAzureMarketplacePrivateOfferTypeFromValue(v string) (*AzureMarketplacePrivateOfferType, error) {
	ev := AzureMarketplacePrivateOfferType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AzureMarketplacePrivateOfferType: valid values are %v", v, AllowedAzureMarketplacePrivateOfferTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AzureMarketplacePrivateOfferType) IsValid() bool {
	for _, existing := range AllowedAzureMarketplacePrivateOfferTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AzureMarketplacePrivateOfferType value
func (v AzureMarketplacePrivateOfferType) Ptr() *AzureMarketplacePrivateOfferType {
	return &v
}

type NullableAzureMarketplacePrivateOfferType struct {
	value *AzureMarketplacePrivateOfferType
	isSet bool
}

func (v NullableAzureMarketplacePrivateOfferType) Get() *AzureMarketplacePrivateOfferType {
	return v.value
}

func (v *NullableAzureMarketplacePrivateOfferType) Set(val *AzureMarketplacePrivateOfferType) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureMarketplacePrivateOfferType) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureMarketplacePrivateOfferType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureMarketplacePrivateOfferType(val *AzureMarketplacePrivateOfferType) *NullableAzureMarketplacePrivateOfferType {
	return &NullableAzureMarketplacePrivateOfferType{value: val, isSet: true}
}

func (v NullableAzureMarketplacePrivateOfferType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureMarketplacePrivateOfferType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
