/*
Suger API

CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

API version: 1.0
Contact: support@suger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package suger

import (
	"encoding/json"
)

// checks if the GcpMarketplacePrivateOfferMetricDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpMarketplacePrivateOfferMetricDetail{}

// GcpMarketplacePrivateOfferMetricDetail struct for GcpMarketplacePrivateOfferMetricDetail
type GcpMarketplacePrivateOfferMetricDetail struct {
	// such as \"CPU\"
	DisplayName *string `json:"displayName,omitempty"`
	// in format of \"projects/{projectNumber}/services/service-name.endpoints.gcp-project-id.cloud.goog\"
	ParentCommerceService *string `json:"parentCommerceService,omitempty"`
	// such as \"BC1B-6259-BF57\"
	SkuId *string `json:"skuId,omitempty"`
	// Price tiers for this metric.
	Tiers []GcpPriceTier `json:"tiers,omitempty"`
	// such as \"minute\"
	UnitDescription *string `json:"unitDescription,omitempty"`
}

// NewGcpMarketplacePrivateOfferMetricDetail instantiates a new GcpMarketplacePrivateOfferMetricDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpMarketplacePrivateOfferMetricDetail() *GcpMarketplacePrivateOfferMetricDetail {
	this := GcpMarketplacePrivateOfferMetricDetail{}
	return &this
}

// NewGcpMarketplacePrivateOfferMetricDetailWithDefaults instantiates a new GcpMarketplacePrivateOfferMetricDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpMarketplacePrivateOfferMetricDetailWithDefaults() *GcpMarketplacePrivateOfferMetricDetail {
	this := GcpMarketplacePrivateOfferMetricDetail{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *GcpMarketplacePrivateOfferMetricDetail) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetParentCommerceService returns the ParentCommerceService field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetParentCommerceService() string {
	if o == nil || IsNil(o.ParentCommerceService) {
		var ret string
		return ret
	}
	return *o.ParentCommerceService
}

// GetParentCommerceServiceOk returns a tuple with the ParentCommerceService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetParentCommerceServiceOk() (*string, bool) {
	if o == nil || IsNil(o.ParentCommerceService) {
		return nil, false
	}
	return o.ParentCommerceService, true
}

// HasParentCommerceService returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) HasParentCommerceService() bool {
	if o != nil && !IsNil(o.ParentCommerceService) {
		return true
	}

	return false
}

// SetParentCommerceService gets a reference to the given string and assigns it to the ParentCommerceService field.
func (o *GcpMarketplacePrivateOfferMetricDetail) SetParentCommerceService(v string) {
	o.ParentCommerceService = &v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetSkuId() string {
	if o == nil || IsNil(o.SkuId) {
		var ret string
		return ret
	}
	return *o.SkuId
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetSkuIdOk() (*string, bool) {
	if o == nil || IsNil(o.SkuId) {
		return nil, false
	}
	return o.SkuId, true
}

// HasSkuId returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) HasSkuId() bool {
	if o != nil && !IsNil(o.SkuId) {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given string and assigns it to the SkuId field.
func (o *GcpMarketplacePrivateOfferMetricDetail) SetSkuId(v string) {
	o.SkuId = &v
}

// GetTiers returns the Tiers field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetTiers() []GcpPriceTier {
	if o == nil || IsNil(o.Tiers) {
		var ret []GcpPriceTier
		return ret
	}
	return o.Tiers
}

// GetTiersOk returns a tuple with the Tiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetTiersOk() ([]GcpPriceTier, bool) {
	if o == nil || IsNil(o.Tiers) {
		return nil, false
	}
	return o.Tiers, true
}

// HasTiers returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) HasTiers() bool {
	if o != nil && !IsNil(o.Tiers) {
		return true
	}

	return false
}

// SetTiers gets a reference to the given []GcpPriceTier and assigns it to the Tiers field.
func (o *GcpMarketplacePrivateOfferMetricDetail) SetTiers(v []GcpPriceTier) {
	o.Tiers = v
}

// GetUnitDescription returns the UnitDescription field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetUnitDescription() string {
	if o == nil || IsNil(o.UnitDescription) {
		var ret string
		return ret
	}
	return *o.UnitDescription
}

// GetUnitDescriptionOk returns a tuple with the UnitDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) GetUnitDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.UnitDescription) {
		return nil, false
	}
	return o.UnitDescription, true
}

// HasUnitDescription returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferMetricDetail) HasUnitDescription() bool {
	if o != nil && !IsNil(o.UnitDescription) {
		return true
	}

	return false
}

// SetUnitDescription gets a reference to the given string and assigns it to the UnitDescription field.
func (o *GcpMarketplacePrivateOfferMetricDetail) SetUnitDescription(v string) {
	o.UnitDescription = &v
}

func (o GcpMarketplacePrivateOfferMetricDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpMarketplacePrivateOfferMetricDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.ParentCommerceService) {
		toSerialize["parentCommerceService"] = o.ParentCommerceService
	}
	if !IsNil(o.SkuId) {
		toSerialize["skuId"] = o.SkuId
	}
	if !IsNil(o.Tiers) {
		toSerialize["tiers"] = o.Tiers
	}
	if !IsNil(o.UnitDescription) {
		toSerialize["unitDescription"] = o.UnitDescription
	}
	return toSerialize, nil
}

type NullableGcpMarketplacePrivateOfferMetricDetail struct {
	value *GcpMarketplacePrivateOfferMetricDetail
	isSet bool
}

func (v NullableGcpMarketplacePrivateOfferMetricDetail) Get() *GcpMarketplacePrivateOfferMetricDetail {
	return v.value
}

func (v *NullableGcpMarketplacePrivateOfferMetricDetail) Set(val *GcpMarketplacePrivateOfferMetricDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpMarketplacePrivateOfferMetricDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpMarketplacePrivateOfferMetricDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpMarketplacePrivateOfferMetricDetail(val *GcpMarketplacePrivateOfferMetricDetail) *NullableGcpMarketplacePrivateOfferMetricDetail {
	return &NullableGcpMarketplacePrivateOfferMetricDetail{value: val, isSet: true}
}

func (v NullableGcpMarketplacePrivateOfferMetricDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpMarketplacePrivateOfferMetricDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
