/*
Suger API

CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

API version: 1.0
Contact: support@suger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GcpMarketplacePrivateOfferTermDurationConstraint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpMarketplacePrivateOfferTermDurationConstraint{}

// GcpMarketplacePrivateOfferTermDurationConstraint struct for GcpMarketplacePrivateOfferTermDurationConstraint
type GcpMarketplacePrivateOfferTermDurationConstraint struct {
	DefaultDuration *GcpPeriodDuration `json:"defaultDuration,omitempty"`
}

// NewGcpMarketplacePrivateOfferTermDurationConstraint instantiates a new GcpMarketplacePrivateOfferTermDurationConstraint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpMarketplacePrivateOfferTermDurationConstraint() *GcpMarketplacePrivateOfferTermDurationConstraint {
	this := GcpMarketplacePrivateOfferTermDurationConstraint{}
	return &this
}

// NewGcpMarketplacePrivateOfferTermDurationConstraintWithDefaults instantiates a new GcpMarketplacePrivateOfferTermDurationConstraint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpMarketplacePrivateOfferTermDurationConstraintWithDefaults() *GcpMarketplacePrivateOfferTermDurationConstraint {
	this := GcpMarketplacePrivateOfferTermDurationConstraint{}
	return &this
}

// GetDefaultDuration returns the DefaultDuration field value if set, zero value otherwise.
func (o *GcpMarketplacePrivateOfferTermDurationConstraint) GetDefaultDuration() GcpPeriodDuration {
	if o == nil || IsNil(o.DefaultDuration) {
		var ret GcpPeriodDuration
		return ret
	}
	return *o.DefaultDuration
}

// GetDefaultDurationOk returns a tuple with the DefaultDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplacePrivateOfferTermDurationConstraint) GetDefaultDurationOk() (*GcpPeriodDuration, bool) {
	if o == nil || IsNil(o.DefaultDuration) {
		return nil, false
	}
	return o.DefaultDuration, true
}

// HasDefaultDuration returns a boolean if a field has been set.
func (o *GcpMarketplacePrivateOfferTermDurationConstraint) HasDefaultDuration() bool {
	if o != nil && !IsNil(o.DefaultDuration) {
		return true
	}

	return false
}

// SetDefaultDuration gets a reference to the given GcpPeriodDuration and assigns it to the DefaultDuration field.
func (o *GcpMarketplacePrivateOfferTermDurationConstraint) SetDefaultDuration(v GcpPeriodDuration) {
	o.DefaultDuration = &v
}

func (o GcpMarketplacePrivateOfferTermDurationConstraint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpMarketplacePrivateOfferTermDurationConstraint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultDuration) {
		toSerialize["defaultDuration"] = o.DefaultDuration
	}
	return toSerialize, nil
}

type NullableGcpMarketplacePrivateOfferTermDurationConstraint struct {
	value *GcpMarketplacePrivateOfferTermDurationConstraint
	isSet bool
}

func (v NullableGcpMarketplacePrivateOfferTermDurationConstraint) Get() *GcpMarketplacePrivateOfferTermDurationConstraint {
	return v.value
}

func (v *NullableGcpMarketplacePrivateOfferTermDurationConstraint) Set(val *GcpMarketplacePrivateOfferTermDurationConstraint) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpMarketplacePrivateOfferTermDurationConstraint) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpMarketplacePrivateOfferTermDurationConstraint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpMarketplacePrivateOfferTermDurationConstraint(val *GcpMarketplacePrivateOfferTermDurationConstraint) *NullableGcpMarketplacePrivateOfferTermDurationConstraint {
	return &NullableGcpMarketplacePrivateOfferTermDurationConstraint{value: val, isSet: true}
}

func (v NullableGcpMarketplacePrivateOfferTermDurationConstraint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpMarketplacePrivateOfferTermDurationConstraint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
