/*
Suger API

CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

API version: 1.0
Contact: support@suger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice{}

// GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice struct for GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice
type GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice struct {
	DiscountTemplate *GcpPriceModelDiscountTemplate `json:"discountTemplate,omitempty"`
	Period           *GcpPeriodDuration             `json:"period,omitempty"`
}

// NewGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice instantiates a new GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice() *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice {
	this := GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice{}
	return &this
}

// NewGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPriceWithDefaults instantiates a new GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPriceWithDefaults() *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice {
	this := GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice{}
	return &this
}

// GetDiscountTemplate returns the DiscountTemplate field value if set, zero value otherwise.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) GetDiscountTemplate() GcpPriceModelDiscountTemplate {
	if o == nil || IsNil(o.DiscountTemplate) {
		var ret GcpPriceModelDiscountTemplate
		return ret
	}
	return *o.DiscountTemplate
}

// GetDiscountTemplateOk returns a tuple with the DiscountTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) GetDiscountTemplateOk() (*GcpPriceModelDiscountTemplate, bool) {
	if o == nil || IsNil(o.DiscountTemplate) {
		return nil, false
	}
	return o.DiscountTemplate, true
}

// HasDiscountTemplate returns a boolean if a field has been set.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) HasDiscountTemplate() bool {
	if o != nil && !IsNil(o.DiscountTemplate) {
		return true
	}

	return false
}

// SetDiscountTemplate gets a reference to the given GcpPriceModelDiscountTemplate and assigns it to the DiscountTemplate field.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) SetDiscountTemplate(v GcpPriceModelDiscountTemplate) {
	o.DiscountTemplate = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) GetPeriod() GcpPeriodDuration {
	if o == nil || IsNil(o.Period) {
		var ret GcpPeriodDuration
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) GetPeriodOk() (*GcpPeriodDuration, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given GcpPeriodDuration and assigns it to the Period field.
func (o *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) SetPeriod(v GcpPeriodDuration) {
	o.Period = &v
}

func (o GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiscountTemplate) {
		toSerialize["discountTemplate"] = o.DiscountTemplate
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	return toSerialize, nil
}

type NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice struct {
	value *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice
	isSet bool
}

func (v NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) Get() *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice {
	return v.value
}

func (v *NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) Set(val *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice(val *GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) *NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice {
	return &NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice{value: val, isSet: true}
}

func (v NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateFixedPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
