/*
Suger API

CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

API version: 1.0
Contact: support@suger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue{}

// ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue struct for ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue
type ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue struct {
	DisplayName *string `json:"DisplayName,omitempty"`
	Max *string `json:"Max,omitempty"`
	Min *string `json:"Min,omitempty"`
	Remark *string `json:"Remark,omitempty"`
	Step *string `json:"Step,omitempty"`
	Type *string `json:"Type,omitempty"`
	Value *string `json:"Value,omitempty"`
}

// NewClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue instantiates a new ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue() *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue {
	this := ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue{}
	return &this
}

// NewClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValueWithDefaults instantiates a new ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValueWithDefaults() *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue {
	this := ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetMax() string {
	if o == nil || IsNil(o.Max) {
		var ret string
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetMaxOk() (*string, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given string and assigns it to the Max field.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) SetMax(v string) {
	o.Max = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetMin() string {
	if o == nil || IsNil(o.Min) {
		var ret string
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetMinOk() (*string, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given string and assigns it to the Min field.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) SetMin(v string) {
	o.Min = &v
}

// GetRemark returns the Remark field value if set, zero value otherwise.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetRemark() string {
	if o == nil || IsNil(o.Remark) {
		var ret string
		return ret
	}
	return *o.Remark
}

// GetRemarkOk returns a tuple with the Remark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetRemarkOk() (*string, bool) {
	if o == nil || IsNil(o.Remark) {
		return nil, false
	}
	return o.Remark, true
}

// HasRemark returns a boolean if a field has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) HasRemark() bool {
	if o != nil && !IsNil(o.Remark) {
		return true
	}

	return false
}

// SetRemark gets a reference to the given string and assigns it to the Remark field.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) SetRemark(v string) {
	o.Remark = &v
}

// GetStep returns the Step field value if set, zero value otherwise.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetStep() string {
	if o == nil || IsNil(o.Step) {
		var ret string
		return ret
	}
	return *o.Step
}

// GetStepOk returns a tuple with the Step field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetStepOk() (*string, bool) {
	if o == nil || IsNil(o.Step) {
		return nil, false
	}
	return o.Step, true
}

// HasStep returns a boolean if a field has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) HasStep() bool {
	if o != nil && !IsNil(o.Step) {
		return true
	}

	return false
}

// SetStep gets a reference to the given string and assigns it to the Step field.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) SetStep(v string) {
	o.Step = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) SetValue(v string) {
	o.Value = &v
}

func (o ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["DisplayName"] = o.DisplayName
	}
	if !IsNil(o.Max) {
		toSerialize["Max"] = o.Max
	}
	if !IsNil(o.Min) {
		toSerialize["Min"] = o.Min
	}
	if !IsNil(o.Remark) {
		toSerialize["Remark"] = o.Remark
	}
	if !IsNil(o.Step) {
		toSerialize["Step"] = o.Step
	}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if !IsNil(o.Value) {
		toSerialize["Value"] = o.Value
	}
	return toSerialize, nil
}

type NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue struct {
	value *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue
	isSet bool
}

func (v NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) Get() *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue {
	return v.value
}

func (v *NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) Set(val *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) {
	v.value = val
	v.isSet = true
}

func (v NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) IsSet() bool {
	return v.isSet
}

func (v *NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue(val *ClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) *NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue {
	return &NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue{value: val, isSet: true}
}

func (v NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientDescribeInstanceResponseBodyModulesModulePropertiesPropertyPropertyValuesPropertyValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


