/*
Suger API

CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

API version: 1.0
Contact: support@suger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HubspotCrmIntegration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HubspotCrmIntegration{}

// HubspotCrmIntegration struct for HubspotCrmIntegration
type HubspotCrmIntegration struct {
	CompanyFields []string `json:"companyFields,omitempty"`
	ContactFields []string `json:"contactFields,omitempty"`
	Credential *HubspotCrmCredential `json:"credential,omitempty"`
	DealFields []string `json:"dealFields,omitempty"`
	// Paused means the integration is not syncing.
	Paused *bool `json:"paused,omitempty"`
	// Hubspot Account Id
	PortalId *int32 `json:"portalId,omitempty"`
	SecretKey *string `json:"secretKey,omitempty"`
	// Can have at most 3 filters which will all be AND-ed.
	SyncFilters []HubspotSyncFilter `json:"syncFilters,omitempty"`
}

// NewHubspotCrmIntegration instantiates a new HubspotCrmIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHubspotCrmIntegration() *HubspotCrmIntegration {
	this := HubspotCrmIntegration{}
	return &this
}

// NewHubspotCrmIntegrationWithDefaults instantiates a new HubspotCrmIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHubspotCrmIntegrationWithDefaults() *HubspotCrmIntegration {
	this := HubspotCrmIntegration{}
	return &this
}

// GetCompanyFields returns the CompanyFields field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetCompanyFields() []string {
	if o == nil || IsNil(o.CompanyFields) {
		var ret []string
		return ret
	}
	return o.CompanyFields
}

// GetCompanyFieldsOk returns a tuple with the CompanyFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetCompanyFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.CompanyFields) {
		return nil, false
	}
	return o.CompanyFields, true
}

// HasCompanyFields returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasCompanyFields() bool {
	if o != nil && !IsNil(o.CompanyFields) {
		return true
	}

	return false
}

// SetCompanyFields gets a reference to the given []string and assigns it to the CompanyFields field.
func (o *HubspotCrmIntegration) SetCompanyFields(v []string) {
	o.CompanyFields = v
}

// GetContactFields returns the ContactFields field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetContactFields() []string {
	if o == nil || IsNil(o.ContactFields) {
		var ret []string
		return ret
	}
	return o.ContactFields
}

// GetContactFieldsOk returns a tuple with the ContactFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetContactFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.ContactFields) {
		return nil, false
	}
	return o.ContactFields, true
}

// HasContactFields returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasContactFields() bool {
	if o != nil && !IsNil(o.ContactFields) {
		return true
	}

	return false
}

// SetContactFields gets a reference to the given []string and assigns it to the ContactFields field.
func (o *HubspotCrmIntegration) SetContactFields(v []string) {
	o.ContactFields = v
}

// GetCredential returns the Credential field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetCredential() HubspotCrmCredential {
	if o == nil || IsNil(o.Credential) {
		var ret HubspotCrmCredential
		return ret
	}
	return *o.Credential
}

// GetCredentialOk returns a tuple with the Credential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetCredentialOk() (*HubspotCrmCredential, bool) {
	if o == nil || IsNil(o.Credential) {
		return nil, false
	}
	return o.Credential, true
}

// HasCredential returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasCredential() bool {
	if o != nil && !IsNil(o.Credential) {
		return true
	}

	return false
}

// SetCredential gets a reference to the given HubspotCrmCredential and assigns it to the Credential field.
func (o *HubspotCrmIntegration) SetCredential(v HubspotCrmCredential) {
	o.Credential = &v
}

// GetDealFields returns the DealFields field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetDealFields() []string {
	if o == nil || IsNil(o.DealFields) {
		var ret []string
		return ret
	}
	return o.DealFields
}

// GetDealFieldsOk returns a tuple with the DealFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetDealFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.DealFields) {
		return nil, false
	}
	return o.DealFields, true
}

// HasDealFields returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasDealFields() bool {
	if o != nil && !IsNil(o.DealFields) {
		return true
	}

	return false
}

// SetDealFields gets a reference to the given []string and assigns it to the DealFields field.
func (o *HubspotCrmIntegration) SetDealFields(v []string) {
	o.DealFields = v
}

// GetPaused returns the Paused field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetPaused() bool {
	if o == nil || IsNil(o.Paused) {
		var ret bool
		return ret
	}
	return *o.Paused
}

// GetPausedOk returns a tuple with the Paused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetPausedOk() (*bool, bool) {
	if o == nil || IsNil(o.Paused) {
		return nil, false
	}
	return o.Paused, true
}

// HasPaused returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasPaused() bool {
	if o != nil && !IsNil(o.Paused) {
		return true
	}

	return false
}

// SetPaused gets a reference to the given bool and assigns it to the Paused field.
func (o *HubspotCrmIntegration) SetPaused(v bool) {
	o.Paused = &v
}

// GetPortalId returns the PortalId field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetPortalId() int32 {
	if o == nil || IsNil(o.PortalId) {
		var ret int32
		return ret
	}
	return *o.PortalId
}

// GetPortalIdOk returns a tuple with the PortalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetPortalIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PortalId) {
		return nil, false
	}
	return o.PortalId, true
}

// HasPortalId returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasPortalId() bool {
	if o != nil && !IsNil(o.PortalId) {
		return true
	}

	return false
}

// SetPortalId gets a reference to the given int32 and assigns it to the PortalId field.
func (o *HubspotCrmIntegration) SetPortalId(v int32) {
	o.PortalId = &v
}

// GetSecretKey returns the SecretKey field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetSecretKey() string {
	if o == nil || IsNil(o.SecretKey) {
		var ret string
		return ret
	}
	return *o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetSecretKeyOk() (*string, bool) {
	if o == nil || IsNil(o.SecretKey) {
		return nil, false
	}
	return o.SecretKey, true
}

// HasSecretKey returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasSecretKey() bool {
	if o != nil && !IsNil(o.SecretKey) {
		return true
	}

	return false
}

// SetSecretKey gets a reference to the given string and assigns it to the SecretKey field.
func (o *HubspotCrmIntegration) SetSecretKey(v string) {
	o.SecretKey = &v
}

// GetSyncFilters returns the SyncFilters field value if set, zero value otherwise.
func (o *HubspotCrmIntegration) GetSyncFilters() []HubspotSyncFilter {
	if o == nil || IsNil(o.SyncFilters) {
		var ret []HubspotSyncFilter
		return ret
	}
	return o.SyncFilters
}

// GetSyncFiltersOk returns a tuple with the SyncFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HubspotCrmIntegration) GetSyncFiltersOk() ([]HubspotSyncFilter, bool) {
	if o == nil || IsNil(o.SyncFilters) {
		return nil, false
	}
	return o.SyncFilters, true
}

// HasSyncFilters returns a boolean if a field has been set.
func (o *HubspotCrmIntegration) HasSyncFilters() bool {
	if o != nil && !IsNil(o.SyncFilters) {
		return true
	}

	return false
}

// SetSyncFilters gets a reference to the given []HubspotSyncFilter and assigns it to the SyncFilters field.
func (o *HubspotCrmIntegration) SetSyncFilters(v []HubspotSyncFilter) {
	o.SyncFilters = v
}

func (o HubspotCrmIntegration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HubspotCrmIntegration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompanyFields) {
		toSerialize["companyFields"] = o.CompanyFields
	}
	if !IsNil(o.ContactFields) {
		toSerialize["contactFields"] = o.ContactFields
	}
	if !IsNil(o.Credential) {
		toSerialize["credential"] = o.Credential
	}
	if !IsNil(o.DealFields) {
		toSerialize["dealFields"] = o.DealFields
	}
	if !IsNil(o.Paused) {
		toSerialize["paused"] = o.Paused
	}
	if !IsNil(o.PortalId) {
		toSerialize["portalId"] = o.PortalId
	}
	if !IsNil(o.SecretKey) {
		toSerialize["secretKey"] = o.SecretKey
	}
	if !IsNil(o.SyncFilters) {
		toSerialize["syncFilters"] = o.SyncFilters
	}
	return toSerialize, nil
}

type NullableHubspotCrmIntegration struct {
	value *HubspotCrmIntegration
	isSet bool
}

func (v NullableHubspotCrmIntegration) Get() *HubspotCrmIntegration {
	return v.value
}

func (v *NullableHubspotCrmIntegration) Set(val *HubspotCrmIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableHubspotCrmIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableHubspotCrmIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHubspotCrmIntegration(val *HubspotCrmIntegration) *NullableHubspotCrmIntegration {
	return &NullableHubspotCrmIntegration{value: val, isSet: true}
}

func (v NullableHubspotCrmIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHubspotCrmIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


